/* Generated By:JavaCC: Do not edit this line. RuleCompilerTreeConstants.java Version 4.2 */
package by.bsu.fami.etl.compiler.jcc;

public interface RuleCompilerTreeConstants
{
  public int JJTRULE = 0;
  public int JJTPROPERTY = 1;
  public int JJTFIELD = 2;
  public int JJTREADER = 3;
  public int JJTTRANSFORMER = 4;
  public int JJTCHECKER = 5;
  public int JJTFILTER = 6;
  public int JJTTRANSACTONTYPE = 7;
  public int JJTWRITER = 8;
  public int JJTDATASOURCE = 9;
  public int JJTTYPESPECIFIER = 10;
  public int JJTTYPEDEFNAME = 11;
  public int JJTTYPE = 12;
  public int JJTPRIMITIVETYPE = 13;
  public int JJTREFERENCETYPE = 14;
  public int JJTCLASSORINTERFACETYPE = 15;
  public int JJTTYPEARGUMENTS = 16;
  public int JJTTYPEARGUMENT = 17;
  public int JJTWILDCARDBOUNDS = 18;
  public int JJTTYPEBOUND = 19;
  public int JJTMETHODDECLARATION = 20;
  public int JJTFORMALPARAMETERS = 21;
  public int JJTFORMALPARAMETER = 22;
  public int JJTRESULTTYPE = 23;


  public String[] jjtNodeName = {
    "Rule",
    "Property",
    "Field",
    "Reader",
    "Transformer",
    "Checker",
    "Filter",
    "TransactonType",
    "Writer",
    "DataSource",
    "TypeSpecifier",
    "TypedefName",
    "Type",
    "PrimitiveType",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "WildcardBounds",
    "TypeBound",
    "MethodDeclaration",
    "FormalParameters",
    "FormalParameter",
    "ResultType",
  };
}
/* JavaCC - OriginalChecksum=25eb907551248feff1de12974bc2ecf6 (do not edit this line) */
